from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
ASSETS_DIR = APP_DIR / "assets"

COMPANY = {
    "name": "Nébula Security",
    "product": "NébulaVault",
    "tagline": "Gestor local de credenciales",
    "objective": (
        "NébulaVault es una aplicación de escritorio orientada a la gestión segura de "
        "credenciales de acceso de forma local.\n\n"
        "La Aplicación permite crear, abrir y administrar una bóveda digital con registros "
        "de credenciales, aplicando principios de control de acceso y minimización de datos. "
        "Toda la operación se realiza en el dispositivo del usuario, sin sincronización en la nube "
        "ni transmisión de información a servidores externos.\n\n"
        "El propósito del producto es brindar una experiencia clara y confiable para organizar "
        "credenciales, notas asociadas y metadatos, bajo un esquema de protección local que depende "
        "de una contraseña maestra definida por el usuario."
    ),
    "logo_path": ASSETS_DIR / "logo.png",
}

LEGAL_TEXTS = {
    "Aviso de privacidad": (
        "AVISO DE PRIVACIDAD\n"
        "Nébula Security (\"Nébula Security\") pone a disposición la aplicación de escritorio "
        "NébulaVault (la \"Aplicación\"). Este Aviso de privacidad describe cómo se tratan los datos "
        "cuando el usuario utiliza la Aplicación.\n\n"
        "1) Responsable y alcance\n"
        "Nébula Security es responsable del tratamiento de la información que el usuario capture "
        "dentro de la Aplicación. El tratamiento se realiza de forma local en el equipo del usuario.\n\n"
        "2) Información tratada\n"
        "La Aplicación permite al usuario almacenar información asociada a entradas de bóveda, "
        "como: nombre del servicio/sitio, usuario, contraseña, notas, etiquetas y otros campos "
        "definidos por el usuario (en conjunto, \"Datos de la bóveda\").\n\n"
        "3) Finalidades\n"
        "Los Datos de la bóveda se tratan exclusivamente para:\n"
        "• Permitir la creación, apertura y administración de una bóveda local.\n"
        "• Mostrar, organizar, buscar, editar y eliminar entradas de credenciales.\n"
        "• Mantener la integridad de la información mediante controles locales de la Aplicación.\n\n"
        "4) Operación local y ausencia de transmisión\n"
        "La Aplicación opera localmente y, por diseño:\n"
        "• No recopila datos de forma automática para enviarlos a terceros.\n"
        "• No transmite los Datos de la bóveda por internet.\n"
        "• No se integra con servicios en la nube ni con servidores externos para almacenar la bóveda.\n\n"
        "5) Almacenamiento y medidas de protección\n"
        "La bóveda se almacena en el dispositivo del usuario. Para protegerla, la Aplicación utiliza "
        "mecanismos de seguridad locales, incluyendo el uso de una contraseña maestra definida por el "
        "usuario y el cifrado del contenido de la bóveda, de modo que el acceso a los datos requiera "
        "la autenticación correspondiente.\n\n"
        "6) Conservación y eliminación\n"
        "Los datos se conservan mientras la bóveda exista en el equipo del usuario. El usuario puede "
        "eliminar información borrando entradas desde la Aplicación o eliminando la bóveda. La "
        "desinstalación de la Aplicación no garantiza, por sí sola, la eliminación de archivos de datos "
        "si estos se encuentran en ubicaciones externas o respaldos del sistema.\n\n"
        "7) Control del usuario\n"
        "El usuario mantiene control sobre sus datos mediante las funciones de administración de la "
        "bóveda (crear, abrir, editar, exportar si aplica, y eliminar). La seguridad final también "
        "depende de las prácticas del usuario (contraseña maestra robusta, bloqueo del equipo, "
        "actualizaciones del sistema, y protección contra malware).\n\n"
        "8) Cambios a este Aviso\n"
        "Nébula Security podrá actualizar este Aviso para reflejar cambios operativos o normativos. "
        "La versión vigente estará disponible dentro de la Aplicación.\n\n"
        "Última actualización: 6 de febrero de 2026."
    ),

    "Acuerdo de confidencialidad": (
        "ACUERDO DE CONFIDENCIALIDAD\n"
        "Este Acuerdo de Confidencialidad (\"Acuerdo\") aplica a personas que acceden a NébulaVault "
        "en contextos de evaluación, revisión, demostración o pruebas controladas, cuando Nébula Security "
        "lo requiera como condición de acceso.\n\n"
        "1) Información Confidencial\n"
        "Se considera \"Información Confidencial\" toda información no pública relacionada con:\n"
        "• La Aplicación, su diseño, interfaz, flujos, textos, identidad visual y documentación.\n"
        "• Especificaciones, arquitectura, modelos, decisiones técnicas, material interno y know-how.\n"
        "• Material compartido por Nébula Security para evaluación (builds, enlaces privados, manuales, "
        "capturas, diagramas, archivos, credenciales de prueba o procedimientos).\n\n"
        "2) Obligaciones\n"
        "La persona evaluadora se obliga a:\n"
        "• Usar la Información Confidencial únicamente para el propósito autorizado.\n"
        "• No divulgar, publicar, distribuir o poner a disposición de terceros la Información Confidencial.\n"
        "• Proteger la Información Confidencial con medidas razonables para evitar accesos no autorizados.\n\n"
        "3) Restricciones\n"
        "Salvo autorización expresa por escrito de Nébula Security, queda prohibido:\n"
        "• Compartir públicamente capturas, grabaciones, binarios, materiales o documentación no pública.\n"
        "• Realizar ingeniería inversa o descompilación con fines de publicación o explotación no autorizada.\n"
        "• Usar marca, nombres, logotipos o materiales de la Aplicación para fines ajenos al propósito autorizado.\n\n"
        "4) Divulgación responsable\n"
        "Si se detectan fallos, errores o vulnerabilidades, la persona evaluadora se compromete a "
        "reportarlos de forma responsable a Nébula Security y a no divulgarlos públicamente hasta recibir "
        "instrucciones o autorización.\n\n"
        "5) Exclusiones\n"
        "No será Información Confidencial aquella que:\n"
        "• Sea pública sin incumplimiento de este Acuerdo.\n"
        "• Haya sido obtenida legítimamente de un tercero sin obligación de confidencialidad.\n\n"
        "6) Vigencia\n"
        "Las obligaciones de confidencialidad se mantienen durante el acceso y continúan respecto de la "
        "Información Confidencial a la que se haya tenido acceso.\n\n"
        "Última actualización: 6 de febrero de 2026."
    ),

    "Términos de uso": (
        "TÉRMINOS DE USO\n"
        "Al instalar, abrir o utilizar NébulaVault (la \"Aplicación\"), el usuario acepta estos Términos de uso. "
        "Si no está de acuerdo, debe abstenerse de utilizar la Aplicación.\n\n"
        "1) Uso permitido\n"
        "La Aplicación está destinada a la administración local de credenciales y datos asociados. El usuario "
        "se compromete a usarla de forma lícita y conforme a estos Términos.\n\n"
        "2) Seguridad y responsabilidad del usuario\n"
        "La protección de la bóveda depende de la contraseña maestra y del control del dispositivo. El usuario "
        "acepta:\n"
        "• Definir una contraseña maestra robusta y no compartirla.\n"
        "• Proteger su equipo (bloqueo de sesión, actualizaciones, antivirus/antimalware cuando corresponda).\n"
        "• Comprender que el acceso al equipo por terceros, malware o copias no controladas puede comprometer datos.\n\n"
        "3) Propiedad intelectual\n"
        "La Aplicación, sus componentes, marca, diseño, textos y materiales asociados son propiedad de Nébula Security "
        "o se usan bajo licencias aplicables. Se prohíbe copiar, modificar, redistribuir o explotar comercialmente "
        "la Aplicación sin autorización.\n\n"
        "4) Restricciones\n"
        "Queda prohibido:\n"
        "• Usar la Aplicación para actividades ilícitas o para vulnerar derechos de terceros.\n"
        "• Intentar eludir medidas de seguridad, manipular la bóveda o acceder a datos sin autorización.\n"
        "• Descompilar, realizar ingeniería inversa o alterar la Aplicación cuando lo prohíba la legislación aplicable.\n\n"
        "5) Respaldo y disponibilidad\n"
        "El usuario es responsable de administrar sus respaldos si decide realizarlos. La Aplicación puede depender "
        "del entorno del sistema (permisos, rutas, almacenamiento). Nébula Security no garantiza recuperación de datos "
        "por fallos del equipo, eliminación accidental o configuraciones del usuario.\n\n"
        "6) Exclusión de garantías\n"
        "La Aplicación se proporciona \"tal cual\" (as-is), sin garantías expresas de comerciabilidad, idoneidad para "
        "un propósito particular o ausencia total de errores, en la medida permitida por la legislación aplicable.\n\n"
        "7) Limitación de responsabilidad\n"
        "En la medida permitida por la legislación aplicable, Nébula Security no será responsable por daños directos o "
        "indirectos derivados del uso o imposibilidad de uso de la Aplicación, incluyendo pérdida de datos por causas "
        "externas (fallos del sistema, accesos no autorizados al equipo, malware, respaldos inseguros o errores del usuario).\n\n"
        "8) Cambios a los Términos\n"
        "Estos Términos pueden actualizarse. La versión vigente estará disponible dentro de la Aplicación.\n\n"
        "Última actualización: 6 de febrero de 2026."
    ),
}
